package: ycom_login_as
version: '2.0.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/ycom_impersonate
page:
    title: 'translate:ycom_login_as_title'
    block: ycom
    perm: ycom_login_as[]
    pjax: true
    icon: rex-icon rex-icon-user
    subpages:
        settings:
                title: 'translate:ycom_login_as_settings'
                perm: ycom_login_as[]
        help: { title: 'translate:ycom_login_as_help', itemclass: pull-right, icon: rex-icon fa-question-circle, subPath: README.md}       
requires:
    redaxo: '^5.15.0'
    packages:
        ycom: '>=4.2'
    php:
        version: '>=8.1, <9'
